language: android
jdk: oraclejdk8
sudo: true

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - gcc-4.8
      - g++-4.8
  coverity_scan:
    project:
      name: "LucidFusionLabs/LTerminal-android"
      description: "Android SSH/VNC client with advanced features."
    notification_email: build@lucidfusionlabs.com
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew assembleDebug"

before_install:
  - echo $TRAVIS_OS_NAME
  - echo ${HOME}
  - echo ${TRAVIS_BUILD_DIR}
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - gem install fastlane

before_script:
  - mkdir -p ${HOME}/bin
  - mkdir -p ${ANDROID_HOME}/licenses
  - cp core/script/android-sdk-license ${ANDROID_HOME}/licenses
  - cp /usr/share/libtool/config/config.* core/imports/sqlcipher
  - wget https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip
  - unzip -q android-ndk-r13b-linux-x86_64.zip -d ${HOME}
  - export ANDROID_NDK_HOME=${HOME}/android-ndk-r13b
  - openssl aes-256-cbc -k $ENCRYPTION_PASSWORD -in LTerminal/LTerminal-android/LTerminal_Distribution.keystore.enc -d -a -out LTerminal/LTerminal-android/LTerminal_Distribution.keystore
  - openssl aes-256-cbc -k $ENCRYPTION_PASSWORD -in LTerminal/LTerminal-android/GooglePlayRelease.json.enc -d -a -out LTerminal/LTerminal-android/GooglePlayRelease.json
  - mkdir linux && cd linux
  - CC=gcc-4.8 CXX=g++-4.8 cmake -DCMAKE_TOOLCHAIN_FILE=../core/CMake/LinuxToolchain.cmake -DLFL_CPP11=1 ..
  - make flatc
  - cp core/imports/flatbuffers/flatc ${HOME}/bin
  - cd ../LTerminal/LTerminal-android

script:
  - cd ../..
  - fastlane submit_playalpha

after_success:
  - echo "success"

after_failure:
  - echo "failure"

env:
  global:
  - TERM=dumb
  - secure: GVk8dfsqyMi+V64Qi8m3SC1XqWVlu7a9chBICKvVzM2p5U6ItNCyFGheTsQG5qZZCFYVA4ThlBVvAbDgz8t1s2WMaPK0px2vZC+tkQ5PzV1yrtopFDm5yEwXBwEyz2Ljdmy6uHnGzPNW0sAzxlNy7FKJLIr5M2AXMHq8By3P8TFcZBvMxvLsNjTJpKUqSzYF8tb3jZUL3Y+wyEt+8GrC7ip45AHSV15bLEWHbMRbMgML4BC0FOBC0XqUnYPCcSGItkDkjdWta7E94fQUHmSqgs8RDBL7mrEppVH6jaaXUE7d9+mj9Tb8PShI7AYzjp+jwhwSsUgU/f5G0R3Zbms010ANOrfMMynibuIRRaUVAQsYQlU0lFRBTPKNd9ox9OJv6PTZ2bKX8zjAvavaUcNT6yenOweNV2PG2pduPcz1V2tN5zoItiKkhUCUEJHmGOzEFPGDls8RS/vTZDf9tCkplgE5hrhWO6uTD6de189p5oE7fKy2UZE8j9X8YKzIxxdAiWZrmRyO+KQwUfW+fdQ69YwqAG5R79fovWuDU+GHSA0xoZn9rgH7qD96NMQ9u9e2CnpTzDsxyreqEESQpjzbEk4mkMM7ywvcPRNRv0UA07eTfKXMFlupK/RsTYspYtJB+O9gVaswuXNfkfMetYFL+6BC/51P9T9kNen4MJd98HE=
  - secure: WR5MOTc76YyYadHHQz/jYIBYhi5N63ZK6USDIwM+vv02mNBP1QUQKnY0o4zQ+J/8plrlRp6u75DWGpc1XdKC7/xvJF2LDhsRrNNl8JSgwFghwCpzjSflvNQ3oOZ2D2heKi8UzCDjXV/x4GqblQZUegUxCJNVLwqpx8evfJOu1pzL9iFbjGLtflc10ncOt/e6qDU141P+inTB72DvkWieY33aEjztQj6/XdVHtmofZ/sr3FTNmx7PIlw4duKk6NAz+8EAQqcXkpcv04n8vAkG8njGrVMmHHxEpIehhqquML0uWOcpPXUiBG6w7PBWqXgR4SaXEFRacUdq77vfLIAx0sgvDHFByAG5C7OeF7omWDm3MO1dX3MrBhQma9wQHZ0EdshVWH5oVRpSxf/bIt4msKssyOtkgY8FrK2eM2fX6W3SsNDqdLwdv9VtBSbGqIzqbkAI9/G1JRxgCNTLEXS7zzFsepPKQiJBtdf/n5xRNEp9d+Zb02HSqHHhU4Sd0EeMzH4m2d+gyaDFnHSzXoMceEb9hYO3yHVxpHNEoEWMHSOIBfKPeCdq7izAbK9LbpLaCNnYYzxui2psdIYWvhKUe4qkC2M4iywD+v8Dg0MiFXwdPtPVyjdZJ05uqk4u0FUedVzjemVBTcx2H2RHfSzYjrrGI4gKS3aVPAONkMZYTv8=
  - secure: "UVSS6uWYQvZCd9aCp1VyJA4v3niq7wKLwuqJgofgG2gbpj7Oj2N1lZnn5FfGIqAcPSMxrNMD+3aPJokYaG/WGvoclS4sEXnDaS1m2FOw6Oxd+Nda3JDWwXrDSKVAuW0blEDkGOsnEQufDmSrH42MX+97kjwuNInS/UgiNLkblOeYDcmIxuda/E6/UPYujk9BVVZEbDNN5ymUVw53sGfurAek+3djFjkCxEhFUbxcrMU/K90RSJv+9tvvY2HR4qS2hin47daDGezWuoTnkPBd0U9dSPxQimL2OZMkNxb+FmUPXo06Lib43RaHxYZ061tQtQ5ZZ4dld7o+ygiDnz1UIoP0OZwGseP+zmfB1e9BnjCsRfDSEcI+s5LQ+Et0xbgabOgftt6e8p5ZWW2JwfBqrJTaNGmuUGsSi5n48XFi85kUxb2il0K3n5no6LkWc3t6Lzjg8DZ2JYIYzvcNMQsVDJ/9uDrZjzU89DDI5fYVuJf5T0zUd5VPNuhB3hvFYi0RAMq/1AAvs9nwMBbLIo/M58oIeD/Rm1X/MHlixZynhrzeIE5kQJp+plHN4zFiuacxtWYXHJmcUTw0N4BjXU4r1bWu6HlHuqnra/GvD7eO84R9SI5rsMCymJYRA9VurjLKOWKlwOCENJNYC18yqzJp4l61JWH38qTv73pOQqcDO0k="
