language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23

addons:
  apt:
    sources:
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - gcc-4.8
      - g++-4.8

before_install:
  - echo $TRAVIS_OS_NAME
  - echo ${TRAVIS_BUILD_DIR}

before_script:
  - pwd
  - ls -aFl
  - wget https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip
  - unzip -q android-ndk-r13b-linux-x86_64.zip
  - android-ndk-r13b/build/tools/make_standalone_toolchain.py --arch arm --api 9 --install-dir android-toolchain
  - ls -l android-toolchain/sysroot/usr/include/stdlib.h

script:
  - mkdir linux && cd linux
  - CC=gcc-4.8 CXX=g++-4.8 cmake -DCMAKE_TOOLCHAIN_FILE=../core/CMake/LinuxToolchain.cmake -DLFL_CPP11=1 ..
  - make flatc
  - cd ..
  - mkdir android && cd android
  - cmake -DCMAKE_BUILD_TYPE=Release -DLFL_ANDROID_SDK=${TRAVIS_BUILD_DIR}/android-sdk -DLFL_ANDROID_NDK=${TRAVIS_BUILD_DIR}/android-ndk-r13b -DLFL_ANDROID_ROOT=${TRAVIS_BUILD_DIR}/android-toolchain -DLFL_GRADLE_BIN=${GRADLE_USER_HOME}/bin/gradle -DCMAKE_TOOLCHAIN_FILE=../core/CMake/AndroidToolchain.cmake ..
  - cd LTerminal
  - VERBOSE=1 make

after_success:
  - echo "success"

after_failure:
  - echo "failure"
