language: android

android:
  components:
    - build-tools-23.0.3
    - android-23

before_install:
  - echo $TRAVIS_OS_NAME
  - echo $LANG
  - echo $LC_ALL

before_script:
  - wget https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip
  - unzip -q android-ndk-r13b-linux-x86_64.zip
  - pwd
  - echo $HOME

script:
  - mkdir linux && cd linux
  - cmake -DCMAKE_TOOLCHAIN_FILE=../core/CMake/LinuxToolchain.cmake ..
  - make flatc
  - cd ..
  - mkdir android && cd android
  - cmake -DCMAKE_BUILD_TYPE=Release -DLFL_ANDROID_SDK=${TRAVIS_BUILD_DIR}/android-sdk -DLFL_ANDROID_NDK=${TRAVIS_BUILD_DIR}/android-ndk-r13b -DLFL_ANDROID_ROOT=${TRAVIS_BUILD_DIR}/android-toolchain -DLFL_GRADLE_BIN=${GRADLE_USER_HOME}/bin/gradle -DCMAKE_TOOLCHAIN_FILE=../core/CMake/AndroidToolchain.cmake ..

after_success:
  - echo "success"

after_failure:
  - echo "failure"
